import type { Product, Collection } from './types';
import { IMG, CATEGORY_IMG, C } from './images';

// Each product's `images` array is intentionally aligned with `colors`:
//   images[i] is shown when the user picks colors[i].
// Extra images beyond colors.length are used as the "hover" preview.
//
// Catalog, sizes, colours and prices below come straight from the
// Vee_jeans product line (prices in NGN). Photos are the real product
// shots in /public/catalog/.

const baseProducts: Omit<Product, 'id' | 'slug'>[] = [
  {
    name: 'Belted Denim Jumpsuit',
    category: 'denim-jumpsuit',
    categoryLabel: 'Jumpsuit',
    collection: ['new-arrivals', 'best-sellers', 'premium-turkish'],
    fit: 'slim',
    waist: 'high',
    wash: 'light-blue',
    colors: ['#7fa8d4', '#14213d'],
    colorLabels: ['Sky Blue', 'Dark Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    bodyTypes: ['slim', 'hourglass', 'tall', 'curvy'],
    price: 48375,
    wholesalePrice: 33800,
    minWholesaleQty: 6,
    description:
      'One piece, all confidence. A tailored denim jumpsuit with a belted waist and clean ankle crop — available in our sky blue and dark blue washes.',
    features: ['Belted cinch waist', 'Functional side pockets', 'Hidden back zip', 'Cropped ankle length'],
    fabric: 'Cotton-rich Turkish denim',
    stretchLevel: 2,
    images: [C(46), C(21), C(49), C(44)],
    rating: 4.9,
    reviewCount: 64,
    stock: 30,
    isNew: true,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['New In', 'Editor’s Pick'],
  },
  {
    name: 'Classic Wide Leg Denim',
    category: 'wide-leg-jeans',
    categoryLabel: 'Wide Leg',
    collection: ['new-arrivals', 'trending', 'everyday'],
    fit: 'loose',
    waist: 'high',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Light Blue', 'Mid Blue'],
    sizes: ['6', '8', '10', '12'],
    bodyTypes: ['slim', 'tall', 'athletic', 'rectangle'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'The wide-leg silhouette everyone is reaching for. Premium Turkish denim with a clean high waist and a fluid, floor-skimming leg.',
    features: ['High waist', 'Wide-leg drop', 'Floor-grazing length'],
    fabric: '100% Turkish Cotton',
    stretchLevel: 1,
    images: [C(40), C(43), C(30), C(50)],
    rating: 4.8,
    reviewCount: 156,
    stock: 58,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Trending'],
  },
  {
    name: 'Barrel Leg Jeans',
    category: 'barrel-jeans',
    categoryLabel: 'Barrel Jeans',
    collection: ['new-arrivals', 'trending'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#5d8bbb', '#3c6da3'],
    colorLabels: ['Mid Blue', 'Blue'],
    sizes: ['S', 'M'],
    bodyTypes: ['slim', 'athletic', 'rectangle'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'The curved barrel leg — roomy through the thigh and tapered at the ankle for that sculpted, of-the-moment shape.',
    features: ['Curved barrel leg', 'Tapered ankle', 'Mid rise'],
    fabric: 'Cotton-rich Turkish denim',
    stretchLevel: 2,
    images: [C(3), C(12), C(28), C(25)],
    rating: 4.8,
    reviewCount: 78,
    stock: 36,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Stretch Combat Cargo Jeans',
    category: 'combat-jeans',
    categoryLabel: 'Combat Jeans',
    collection: ['trending', 'tiktok-viral', 'streetwear'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'dark-blue',
    colors: ['#1c3253', '#3c6da3'],
    colorLabels: ['Dark Blue', 'Mid Blue'],
    sizes: ['26', '27', '28', '29', '30'],
    bodyTypes: ['slim', 'athletic', 'curvy', 'rectangle'],
    price: 48375,
    wholesalePrice: 33800,
    minWholesaleQty: 10,
    description:
      'Utility-meets-fashion combat denim with a comfortable stretch. Functional pockets and a relaxed leg you can move in all day.',
    features: ['Stretch denim', 'Combat / cargo pockets', 'Relaxed leg'],
    fabric: '97% Cotton · 3% Elastane',
    stretchLevel: 4,
    images: [C(22), C(47)],
    rating: 4.7,
    reviewCount: 91,
    stock: 40,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Stretch', 'Viral Fit'],
  },
  {
    name: 'Frayed Denim Mini Skirt',
    category: 'denim-skirt',
    categoryLabel: 'Mini Skirt',
    collection: ['new-arrivals', 'trending', 'tiktok-viral', 'weekend'],
    fit: 'slim',
    waist: 'high',
    wash: 'light-blue',
    colors: ['#90b1d4', '#c0d2e8'],
    colorLabels: ['Light Blue', 'Sky Wash'],
    sizes: ['6', '8', '10', '12', '14'],
    bodyTypes: ['slim', 'petite', 'hourglass', 'pear'],
    price: 37625,
    wholesalePrice: 26300,
    minWholesaleQty: 12,
    description:
      'A high-waist denim mini with a raw frayed hem. The flattering everyday skirt that styles with everything.',
    features: ['Mini length', 'Frayed raw hem', 'High waist'],
    fabric: '98% Cotton · 2% Elastane',
    stretchLevel: 2,
    images: [C(23), C(29)],
    rating: 4.7,
    reviewCount: 73,
    stock: 44,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Premium Barrel Jeans',
    category: 'barrel-jeans',
    categoryLabel: 'Barrel Jeans',
    collection: ['premium-turkish', 'limited-edition', 'luxury'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['32', '34', '36'],
    bodyTypes: ['slim', 'athletic', 'rectangle'],
    price: 69875,
    wholesalePrice: 48900,
    minWholesaleQty: 6,
    description:
      'Our premium-grade barrel jean in a deeper wash. Structured rigid denim that holds the sculpted barrel shape beautifully.',
    features: ['Premium rigid denim', 'Sculpted barrel leg', 'Non-stretch'],
    fabric: '100% Premium Turkish Cotton',
    stretchLevel: 1,
    images: [C(25), C(12), C(28)],
    rating: 4.9,
    reviewCount: 41,
    stock: 18,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Premium', 'Limited Drop'],
  },
  {
    name: 'Straight Leg Jeans',
    category: 'straight-leg-jeans',
    categoryLabel: 'Straight Leg',
    collection: ['best-sellers', 'everyday', 'office'],
    fit: 'slim',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Light Blue', 'Mid Blue'],
    sizes: ['6', '8', '10', '12', '14', '16'],
    bodyTypes: ['slim', 'athletic', 'rectangle', 'tall'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'A timeless straight leg in rigid Turkish denim. Clean lines, no stretch — the everyday jean that never dates.',
    features: ['Straight leg', 'Mid rise', 'Non-stretch rigid denim'],
    fabric: '100% Turkish Cotton',
    stretchLevel: 1,
    images: [C(5), C(10), C(38), C(41)],
    rating: 4.8,
    reviewCount: 134,
    stock: 60,
    isBestSeller: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Denim Shorts',
    category: 'denim-shorts',
    categoryLabel: 'Shorts',
    collection: ['new-arrivals', 'weekend'],
    fit: 'slim',
    waist: 'high',
    wash: 'white',
    colors: ['#f3f1ec', '#90b1d4'],
    colorLabels: ['White', 'Light Blue'],
    sizes: ['S', 'M'],
    bodyTypes: ['slim', 'hourglass', 'athletic'],
    price: 32250,
    wholesalePrice: 22600,
    minWholesaleQty: 12,
    description: 'High-waist denim shorts cut to flatter — easy, confident, weekend-ready.',
    features: ['High rise', 'Clean hem', 'Slight stretch'],
    fabric: '98% Cotton · 2% Elastane',
    stretchLevel: 2,
    images: [C(36), C(6)],
    rating: 4.6,
    reviewCount: 52,
    stock: 48,
    isNew: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Denim Skirt',
    category: 'denim-skirt',
    categoryLabel: 'Skirt',
    collection: ['everyday', 'weekend'],
    fit: 'slim',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['6', '8', '10'],
    bodyTypes: ['slim', 'petite', 'hourglass', 'pear'],
    price: 32250,
    wholesalePrice: 22600,
    minWholesaleQty: 12,
    description: 'A clean A-line denim skirt in a rich dark wash. The wardrobe staple that works season to season.',
    features: ['A-line shape', 'High waist', 'Back slit for movement'],
    fabric: '98% Cotton · 2% Elastane',
    stretchLevel: 2,
    images: [C(1), C(14)],
    rating: 4.7,
    reviewCount: 60,
    stock: 40,
    isWholesaleEligible: true,
  },
  {
    name: 'Grey Wide Leg Jeans',
    category: 'wide-leg-jeans',
    categoryLabel: 'Wide Leg',
    collection: ['new-arrivals', 'trending', 'curvy'],
    fit: 'loose',
    waist: 'high',
    wash: 'grey',
    colors: ['#6b6b6b', '#3c6da3'],
    colorLabels: ['Grey', 'Blue'],
    sizes: ['32', '34', '36'],
    bodyTypes: ['curvy', 'tall', 'plus-size', 'hourglass'],
    price: 48375,
    wholesalePrice: 33800,
    minWholesaleQty: 8,
    description:
      'The wide-leg in a moody grey wash, also available in blue. Drapes long and lean from a clean high waist.',
    features: ['Wide-leg drop', 'High waist', 'Grey & blue washes'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [C(45), C(7), C(30)],
    rating: 4.8,
    reviewCount: 70,
    stock: 34,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Midi Denim Skirt',
    category: 'denim-skirt',
    categoryLabel: 'Midi Skirt',
    collection: ['premium-turkish', 'office', 'everyday'],
    fit: 'slim',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#14213d', '#1c3253'],
    colorLabels: ['Midnight', 'Dark Blue'],
    sizes: ['6', '8', '10', '12', '14'],
    bodyTypes: ['slim', 'hourglass', 'curvy', 'pear'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description: 'A mid-length denim skirt that takes you from desk to dinner. Sleek, structured and endlessly wearable.',
    features: ['Midi length', 'High waist', 'Back vent'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [C(14), C(37)],
    rating: 4.8,
    reviewCount: 49,
    stock: 32,
    isWholesaleEligible: true,
  },
  {
    name: 'Maxi Denim Skirt',
    category: 'denim-skirt',
    categoryLabel: 'Maxi Skirt',
    collection: ['premium-turkish', 'luxury', 'best-sellers'],
    fit: 'slim',
    waist: 'super-high',
    wash: 'dark-blue',
    colors: ['#14213d', '#0b1426'],
    colorLabels: ['Midnight', 'Deep Indigo'],
    sizes: ['6', '8', '10', '12', '14'],
    bodyTypes: ['curvy', 'tall', 'hourglass', 'plus-size'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description: 'Floor-grazing maxi denim with a sweeping A-line fall. The statement skirt of the season.',
    features: ['Maxi length', 'Super-high waist', 'A-line sweep'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [C(27), C(20), C(26)],
    rating: 4.9,
    reviewCount: 57,
    stock: 26,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Editor’s Pick'],
  },
  {
    name: 'Denim Corset Top',
    category: 'denim-corset',
    categoryLabel: 'Corset',
    collection: ['trending', 'tiktok-viral', 'new-arrivals'],
    fit: 'slim',
    waist: 'corset',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['S'],
    bodyTypes: ['slim', 'hourglass', 'curvy'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'A sculpted denim corset with a stretch-back fit that cinches and lifts. Pair with our wide-leg or palazzo denim.',
    features: ['Structured corset shape', 'Stretch fit', 'Lace-up / boned detailing'],
    fabric: '95% Cotton · 5% Elastane',
    stretchLevel: 4,
    images: [C(29), C(1)],
    rating: 4.8,
    reviewCount: 38,
    stock: 22,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Stretch', 'Viral Fit'],
  },
  {
    name: 'Relaxed Boyfriend Jeans',
    category: 'boyfriend-jeans',
    categoryLabel: 'Boyfriend Jeans',
    collection: ['streetwear', 'everyday'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Light Blue', 'Mid Blue'],
    sizes: ['36'],
    bodyTypes: ['slim', 'athletic', 'rectangle'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'The borrowed-from-the-boys jean — relaxed through the leg in rigid non-stretch denim for that effortless slouch.',
    features: ['Relaxed boyfriend fit', 'Mid rise', 'Non-stretch'],
    fabric: '100% Turkish Cotton',
    stretchLevel: 1,
    images: [C(10), C(11), C(9)],
    rating: 4.7,
    reviewCount: 44,
    stock: 28,
    isWholesaleEligible: true,
  },
  {
    name: 'Ripped Denim Jeans',
    category: 'ripped-jeans',
    categoryLabel: 'Ripped Jeans',
    collection: ['trending', 'streetwear', 'tiktok-viral'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#90b1d4', '#6b6b6b'],
    colorLabels: ['Light Blue', 'Grey'],
    sizes: ['10'],
    bodyTypes: ['slim', 'athletic', 'rectangle', 'pear'],
    price: 37625,
    wholesalePrice: 26300,
    minWholesaleQty: 12,
    description: 'Hand-finished rips across the knee and thigh on a relaxed leg. Effortless street-ready denim.',
    features: ['Hand-finished distressing', 'Relaxed leg', 'Frayed details'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [C(39), C(7)],
    rating: 4.7,
    reviewCount: 66,
    stock: 30,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Denim Dungaree Shorts',
    category: 'denim-shorts',
    categoryLabel: 'Dungaree Shorts',
    collection: ['weekend', 'streetwear', 'new-arrivals'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#5d8bbb', '#90b1d4'],
    colorLabels: ['Mid Blue', 'Light Blue'],
    sizes: ['8', '10'],
    bodyTypes: ['slim', 'petite', 'athletic'],
    price: 32250,
    wholesalePrice: 22600,
    minWholesaleQty: 12,
    description: 'Playful denim dungaree shorts with adjustable straps and a bib front. Weekend dressing, sorted.',
    features: ['Adjustable straps', 'Bib front pocket', 'Non-stretch'],
    fabric: '100% Cotton',
    stretchLevel: 1,
    images: [C(15)],
    rating: 4.6,
    reviewCount: 35,
    stock: 26,
    isNew: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Rhinestone Denim Jacket',
    category: 'denim-jacket',
    categoryLabel: 'Rhinestone Jacket',
    collection: ['new-arrivals', 'limited-edition', 'streetwear'],
    fit: 'oversized',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Light Blue', 'Mid Blue'],
    sizes: ['S', 'M', 'L'],
    bodyTypes: ['slim', 'tall', 'rectangle', 'curvy'],
    price: 37625,
    wholesalePrice: 26300,
    minWholesaleQty: 8,
    description:
      'A statement denim jacket finished with all-over rhinestones. Runs big for an easy, oversized layer.',
    features: ['All-over rhinestone detail', 'Oversized fit (runs big)', 'Classic trucker silhouette'],
    fabric: '100% Cotton',
    stretchLevel: 1,
    images: [C(32), C(34)],
    rating: 4.8,
    reviewCount: 29,
    stock: 20,
    isNew: true,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Limited Drop', 'Runs Big'],
  },
  {
    name: 'Plus Size Skinny Jeans',
    category: 'skinny-jeans',
    categoryLabel: 'Skinny Jeans',
    collection: ['best-sellers', 'curvy', 'everyday'],
    fit: 'curvy',
    waist: 'high',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Light Blue', 'Mid Blue'],
    sizes: ['24', '26'],
    bodyTypes: ['curvy', 'plus-size', 'hourglass', 'pear'],
    price: 37625,
    wholesalePrice: 26300,
    minWholesaleQty: 12,
    description:
      'Our curve-sculpting skinny, sized up for a true plus fit. Four-way stretch hugs and lifts without the gap.',
    features: ['4-way stretch denim', 'Anti-gap waistband', 'Sculpt-and-lift fit'],
    fabric: '92% Cotton · 6% Polyester · 2% Elastane',
    stretchLevel: 5,
    images: [C(17), C(16), C(19)],
    rating: 4.8,
    reviewCount: 88,
    stock: 42,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Sculpt Fit'],
  },
  {
    name: 'Black Wide Leg Jeans',
    category: 'wide-leg-jeans',
    categoryLabel: 'Wide Leg',
    collection: ['best-sellers', 'streetwear', 'everyday'],
    fit: 'loose',
    waist: 'high',
    wash: 'black',
    colors: ['#1a1a1a', '#3a3a3a'],
    colorLabels: ['Jet Black', 'Charcoal'],
    sizes: ['6', '7', '8', '9', '10', '12', '14'],
    bodyTypes: ['slim', 'curvy', 'tall', 'hourglass', 'rectangle'],
    price: 43000,
    wholesalePrice: 30100,
    minWholesaleQty: 10,
    description:
      'The black wide-leg that goes with everything, with a comfortable stretch and a clean high waist.',
    features: ['Stretch denim', 'Wide-leg drop', 'High waist'],
    fabric: '97% Cotton · 3% Elastane',
    stretchLevel: 4,
    images: [C(4), C(2), C(16)],
    rating: 4.9,
    reviewCount: 142,
    stock: 64,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Stretch', 'Best Seller'],
  },
];

function slugify(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export const PRODUCTS: Product[] = baseProducts.map((p, i) => ({
  ...p,
  id: `vj-${(i + 1).toString().padStart(3, '0')}`,
  slug: slugify(p.name),
}));

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCollection(collection: string, limit?: number) {
  const filtered = PRODUCTS.filter((p) => p.collection.includes(collection));
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getRelatedProducts(product: Product, limit = 4) {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && (p.category === product.category || p.fit === product.fit)
  ).slice(0, limit);
}

export const COLLECTIONS: Collection[] = [
  {
    id: 'c1',
    slug: 'new-arrivals',
    name: 'New Arrivals',
    tagline: 'Fresh denim drops',
    description:
      'The very latest from our Turkish denim mill. Limited stock, fast-moving favorites.',
    cover: IMG.womanDenim1,
    productCount: PRODUCTS.filter((p) => p.collection.includes('new-arrivals')).length,
  },
  {
    id: 'c2',
    slug: 'premium-turkish',
    name: 'Premium Turkish Denim',
    tagline: 'Crafted at the mill',
    description:
      'Our signature edit — every piece sourced from Turkey’s most respected denim mills.',
    cover: IMG.womanDenim7,
    productCount: PRODUCTS.filter((p) => p.collection.includes('premium-turkish')).length,
  },
  {
    id: 'c3',
    slug: 'best-sellers',
    name: 'Best Sellers',
    tagline: 'Loved by 10,000+ women',
    description: 'The styles that keep selling out. Restocked weekly.',
    cover: IMG.womanDenim4,
    productCount: PRODUCTS.filter((p) => p.collection.includes('best-sellers')).length,
  },
  {
    id: 'c4',
    slug: 'curvy',
    name: 'Curvy Collection',
    tagline: 'Made for every curve',
    description:
      'Contoured waistbands, sculpting panels, true plus sizing. Designed with curvy bodies in mind from the start.',
    cover: IMG.womanDenim2,
    productCount: PRODUCTS.filter((p) => p.bodyTypes.includes('curvy')).length,
  },
  {
    id: 'c5',
    slug: 'tiktok-viral',
    name: 'TikTok Viral',
    tagline: 'The pieces breaking the internet',
    description: 'You saw them on your FYP. Now wear them.',
    cover: IMG.womanDenim11,
    productCount: PRODUCTS.filter((p) => p.collection.includes('tiktok-viral')).length,
  },
  {
    id: 'c6',
    slug: 'limited-edition',
    name: 'Limited Edition',
    tagline: 'When they’re gone, they’re gone',
    description: 'Small-batch luxury denim. Numbered drops, no restocks.',
    cover: IMG.womanDenim6,
    productCount: PRODUCTS.filter((p) => p.isLimited).length,
  },
];

// Style category map for "Shop by Style" tiles
export const STYLE_TILES = [
  { name: 'Jumpsuit', slug: 'denim-jumpsuit', image: CATEGORY_IMG.denimJumpsuit },
  { name: 'Wide Leg', slug: 'wide-leg-jeans', image: CATEGORY_IMG.wideLeg },
  { name: 'Barrel Jeans', slug: 'barrel-jeans', image: CATEGORY_IMG.barrelJeans },
  { name: 'Combat Jeans', slug: 'combat-jeans', image: CATEGORY_IMG.combatJeans },
  { name: 'Straight Leg', slug: 'straight-leg-jeans', image: CATEGORY_IMG.straightLeg },
  { name: 'Boyfriend Jeans', slug: 'boyfriend-jeans', image: CATEGORY_IMG.boyfriendJeans },
  { name: 'Skinny Jeans', slug: 'skinny-jeans', image: CATEGORY_IMG.skinnyJeans },
  { name: 'Ripped Jeans', slug: 'ripped-jeans', image: CATEGORY_IMG.ripped },
  { name: 'Denim Skirt', slug: 'denim-skirt', image: CATEGORY_IMG.denimSkirt },
  { name: 'Denim Shorts', slug: 'denim-shorts', image: CATEGORY_IMG.denimShorts },
  { name: 'Denim Corset', slug: 'denim-corset', image: CATEGORY_IMG.denimCorset },
  { name: 'Denim Jacket', slug: 'denim-jacket', image: CATEGORY_IMG.denimJacket },
];

export const BODY_TYPE_TILES = [
  { name: 'Petite Fit', slug: 'petite', image: IMG.womanDenim8, blurb: 'Sized down without sizing out the style.' },
  { name: 'Curvy Fit', slug: 'curvy', image: IMG.womanDenim2, blurb: 'Sculpted waistbands, lifted seats, generous through the thigh.' },
  { name: 'Tall Fit', slug: 'tall', image: IMG.womanDenim9, blurb: 'Extra inches in all the right places.' },
  { name: 'Plus Size', slug: 'plus-size', image: IMG.womanDenim18, blurb: 'Premium denim engineered for a true plus fit.' },
  { name: 'Hourglass', slug: 'hourglass', image: IMG.womanDenim5, blurb: 'Cinches the waist, lifts the rest.' },
  { name: 'Pear Shape', slug: 'pear', image: IMG.womanDenim1, blurb: 'Roomy through the hip with a clean front.' },
];
