import type { Product, Collection } from './types';
import { IMG, CATEGORY_IMG } from './images';

// Each product's `images` array is intentionally aligned with `colors`:
//   images[i] is shown when the user picks colors[i].
// Extra images beyond colors.length are used as the "hover" preview.

const baseProducts: Omit<Product, 'id' | 'slug'>[] = [
  {
    name: 'Premium High Waist Turkish Mom Jeans',
    category: 'mom-jeans',
    categoryLabel: 'Mom Jeans',
    collection: ['new-arrivals', 'premium-turkish', 'best-sellers'],
    fit: 'relaxed',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#1c3253', '#3c6da3', '#14213d', '#5d8bbb'],
    colorLabels: ['Dark Blue', 'Mid Blue', 'Midnight', 'Light Blue'],
    sizes: ['6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
    bodyTypes: ['curvy', 'hourglass', 'pear', 'plus-size'],
    price: 24500,
    comparePrice: 32000,
    wholesalePrice: 16800,
    minWholesaleQty: 12,
    description:
      'Elevate your everyday with our flagship high-waist Turkish mom jeans. Crafted from premium stretch denim, the relaxed-through-the-thigh silhouette tapers gently for a flattering finish on every body type. The reinforced waistband sculpts and supports without digging — the kind of jean you reach for first.',
    features: [
      'Soft 12oz Turkish stretch denim',
      'Reinforced corset-style waistband',
      'YKK zipper & metal Vee_jeans button',
      'Fade-resistant indigo dye',
      'Roomy back pockets for a lifted look',
    ],
    fabric: '98% Cotton · 2% Elastane · Turkish Mill',
    stretchLevel: 3,
    images: [IMG.womanDenim1, IMG.womanDenim2, IMG.womanDenim3, IMG.womanDenim4],
    rating: 4.9,
    reviewCount: 312,
    stock: 84,
    isNew: true,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Editor’s Pick', 'Wholesale Available'],
  },
  {
    name: 'Oversized Baggy Streetwear Denim',
    category: 'baggy-jeans',
    categoryLabel: 'Baggy Jeans',
    collection: ['trending', 'tiktok-viral', 'new-arrivals'],
    fit: 'oversized',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#5d8bbb', '#c0d2e8', '#3c6da3'],
    colorLabels: ['Light Blue', 'Sky Wash', 'Mid Blue'],
    sizes: ['6', '8', '10', '12', '14', '16', '18', '20'],
    bodyTypes: ['slim', 'tall', 'athletic', 'rectangle'],
    price: 27800,
    comparePrice: 35000,
    wholesalePrice: 19200,
    minWholesaleQty: 12,
    description:
      'Designed for bold streetwear lovers. Our oversized baggy denim drops straight from the hip for that effortless off-duty silhouette that took TikTok by storm.',
    features: [
      'Wide-leg drop silhouette',
      'Slouched pockets',
      'Garment-washed for softness',
      'Stacked-length finish',
    ],
    fabric: '100% Cotton · Non-Stretch Turkish Denim',
    stretchLevel: 1,
    images: [IMG.womanDenim2, IMG.womanDenim3, IMG.womanDenim1],
    rating: 4.8,
    reviewCount: 198,
    stock: 56,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Viral Fit', 'New In'],
  },
  {
    name: 'Elegant Palazzo Denim Trousers',
    category: 'palazzo-jeans',
    categoryLabel: 'Palazzo Jeans',
    collection: ['premium-turkish', 'office', 'luxury'],
    fit: 'loose',
    waist: 'super-high',
    wash: 'dark-blue',
    colors: ['#14213d', '#1c3253', '#0b1426'],
    colorLabels: ['Midnight', 'Dark Blue', 'Deep Indigo'],
    sizes: ['6', '8', '10', '12', '14', '16', '18', '20', '22'],
    bodyTypes: ['curvy', 'tall', 'hourglass', 'pear', 'plus-size'],
    price: 29900,
    wholesalePrice: 20500,
    minWholesaleQty: 10,
    description:
      'Sweeping wide-leg palazzos cut from premium Turkish denim. The kind of trouser that elevates a simple tee into an editorial moment.',
    features: [
      'Flowing palazzo silhouette',
      'Hidden side zip closure',
      'Crisp pressed front pleat',
      'Floor-grazing length (hem-able)',
    ],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim7, IMG.womanDenim4, IMG.womanDenim9],
    rating: 4.9,
    reviewCount: 142,
    stock: 38,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Editor’s Pick'],
  },
  {
    name: 'Curve Sculpt High-Rise Skinny',
    category: 'skinny-jeans',
    categoryLabel: 'Skinny Jeans',
    collection: ['best-sellers', 'curvy', 'everyday'],
    fit: 'curvy',
    waist: 'high',
    wash: 'black',
    colors: ['#1a1a1a', '#3a3a3a', '#14213d'],
    colorLabels: ['Jet Black', 'Charcoal', 'Midnight'],
    sizes: ['6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
    bodyTypes: ['curvy', 'hourglass', 'pear', 'plus-size'],
    price: 22500,
    comparePrice: 28000,
    wholesalePrice: 15400,
    minWholesaleQty: 12,
    description:
      'Engineered to hug your curves with our signature 4-way stretch denim. The contoured waistband prevents gapping at the back, while the body-sculpt panels lift and define.',
    features: [
      '4-way Turkish stretch denim',
      'Anti-gap contoured waistband',
      'Sculpt-and-lift back panels',
      'All-day comfort fit',
    ],
    fabric: '92% Cotton · 6% Polyester · 2% Elastane',
    stretchLevel: 5,
    images: [IMG.womanDenim4, IMG.womanDenim10, IMG.womanDenim6],
    rating: 4.9,
    reviewCount: 487,
    stock: 124,
    isBestSeller: true,
    isWholesaleEligible: true,
    tags: ['Best Seller', 'Sculpt Fit'],
  },
  {
    name: 'Wide Leg Vintage Wash Jeans',
    category: 'wide-leg-jeans',
    categoryLabel: 'Wide Leg',
    collection: ['trending', 'new-arrivals', 'tiktok-viral'],
    fit: 'loose',
    waist: 'high',
    wash: 'vintage',
    colors: ['#90b1d4', '#c0d2e8'],
    colorLabels: ['Vintage Blue', 'Faded Wash'],
    sizes: ['6', '8', '10', '12', '14', '16', '18', '20'],
    bodyTypes: ['slim', 'tall', 'athletic', 'rectangle'],
    price: 26500,
    wholesalePrice: 18200,
    minWholesaleQty: 10,
    description:
      'The wide-leg silhouette that’s everywhere right now. Vintage-washed Turkish denim with a perfectly puddled hem.',
    features: ['Vintage hand-wash finish', '24" wide-leg opening', 'Reinforced rivets'],
    fabric: '100% Turkish Cotton',
    stretchLevel: 1,
    images: [IMG.womanDenim9, IMG.womanDenim11, IMG.womanDenim7],
    rating: 4.8,
    reviewCount: 256,
    stock: 67,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Trending'],
  },
  {
    name: 'Distressed Knee Ripped Boyfriend',
    category: 'ripped-jeans',
    categoryLabel: 'Ripped Jeans',
    collection: ['trending', 'streetwear'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'light-blue',
    colors: ['#90b1d4', '#5d8bbb'],
    colorLabels: ['Vintage Blue', 'Mid Wash'],
    sizes: ['6', '8', '10', '12', '14', '16', '18'],
    bodyTypes: ['slim', 'athletic', 'rectangle', 'pear'],
    price: 23800,
    comparePrice: 30000,
    wholesalePrice: 16500,
    minWholesaleQty: 12,
    description:
      'The boyfriend silhouette reimagined with hand-finished distressing across the knees and thighs. Effortless cool.',
    features: ['Hand-finished distressing', 'Boyfriend relaxed fit', 'Frayed hem'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim12, IMG.womanDenim2, IMG.womanDenim3],
    rating: 4.7,
    reviewCount: 167,
    stock: 41,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Cropped Premium Denim Jacket',
    category: 'denim-jacket',
    categoryLabel: 'Denim Jacket',
    collection: ['new-arrivals', 'premium-turkish'],
    fit: 'slim',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    bodyTypes: ['slim', 'petite', 'curvy', 'hourglass'],
    price: 32500,
    wholesalePrice: 22400,
    minWholesaleQty: 8,
    description:
      'Cropped above the waist for the perfect proportion with high-waist denim. Western-inspired stitching and burnished metal buttons.',
    features: ['Cropped silhouette', 'Western yoke stitching', 'Burnished Vee_jeans buttons'],
    fabric: '100% Cotton',
    stretchLevel: 1,
    images: [IMG.womanDenim5, IMG.womanDenim16, IMG.womanDenim4],
    rating: 4.9,
    reviewCount: 89,
    stock: 32,
    isNew: true,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Limited Drop', 'New In'],
  },
  {
    name: 'Oversized Boyfriend Denim Jacket',
    category: 'denim-jacket',
    categoryLabel: 'Denim Jacket',
    collection: ['trending', 'streetwear'],
    fit: 'oversized',
    wash: 'stone',
    colors: ['#c0d2e8', '#90b1d4'],
    colorLabels: ['Stone Wash', 'Faded Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    bodyTypes: ['slim', 'tall', 'rectangle', 'athletic'],
    price: 34900,
    wholesalePrice: 24100,
    minWholesaleQty: 8,
    description:
      'The drop-shoulder oversized jacket layering everyone is wearing right now. Stone-washed for an instant lived-in feel.',
    features: ['Drop-shoulder oversized', 'Stone-washed', 'Hidden chest pockets'],
    fabric: '100% Cotton',
    stretchLevel: 1,
    images: [IMG.womanDenim16, IMG.womanDenim5, IMG.womanDenim2],
    rating: 4.8,
    reviewCount: 112,
    stock: 28,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'High Waist Denim Mini Skirt',
    category: 'denim-skirt',
    categoryLabel: 'Denim Skirt',
    collection: ['new-arrivals', 'trending'],
    fit: 'slim',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#14213d', '#1c3253'],
    colorLabels: ['Midnight', 'Dark Blue'],
    sizes: ['6', '8', '10', '12', '14', '16'],
    bodyTypes: ['slim', 'petite', 'hourglass', 'pear'],
    price: 18500,
    wholesalePrice: 12800,
    minWholesaleQty: 12,
    description:
      'A timeless silhouette. Our high-waist denim mini hits at the most flattering point with the perfect amount of stretch.',
    features: ['Mini length', 'Back slit for movement', 'Slight stretch'],
    fabric: '98% Cotton · 2% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim8, IMG.womanDenim15, IMG.womanDenim17],
    rating: 4.7,
    reviewCount: 92,
    stock: 47,
    isNew: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Maxi Denim Skirt with Side Slit',
    category: 'denim-skirt',
    categoryLabel: 'Denim Skirt',
    collection: ['premium-turkish', 'luxury'],
    fit: 'slim',
    waist: 'super-high',
    wash: 'dark-blue',
    colors: ['#14213d', '#0b1426'],
    colorLabels: ['Midnight', 'Deep Indigo'],
    sizes: ['6', '8', '10', '12', '14', '16', '18'],
    bodyTypes: ['curvy', 'tall', 'hourglass', 'plus-size'],
    price: 26500,
    wholesalePrice: 18200,
    minWholesaleQty: 10,
    description:
      'Floor-length elegance with a thigh-high side slit. Tailored from premium Turkish denim with a corset-cinched waist.',
    features: ['Maxi length', 'Thigh-high side slit', 'Corset waistband'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim17, IMG.womanDenim8, IMG.womanDenim7],
    rating: 4.9,
    reviewCount: 76,
    stock: 24,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Luxury Capsule'],
  },
  {
    name: 'High Waist Denim Booty Shorts',
    category: 'denim-shorts',
    categoryLabel: 'Denim Shorts',
    collection: ['new-arrivals', 'weekend'],
    fit: 'slim',
    waist: 'high',
    wash: 'light-blue',
    colors: ['#90b1d4', '#c0d2e8', '#1a1a1a'],
    colorLabels: ['Vintage Blue', 'Sky Wash', 'Jet Black'],
    sizes: ['6', '8', '10', '12', '14', '16'],
    bodyTypes: ['slim', 'hourglass', 'curvy', 'athletic'],
    price: 16500,
    wholesalePrice: 11400,
    minWholesaleQty: 12,
    description: 'High-waist shorts cut to flatter — never too short, always confident.',
    features: ['High rise', 'Frayed hem', 'Two-way stretch'],
    fabric: '97% Cotton · 3% Elastane',
    stretchLevel: 3,
    images: [IMG.womanDenim15, IMG.womanDenim18, IMG.womanDenim8],
    rating: 4.6,
    reviewCount: 84,
    stock: 62,
    isNew: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Sleeveless Denim Jumpsuit',
    category: 'denim-jumpsuit',
    categoryLabel: 'Denim Jumpsuit',
    collection: ['luxury', 'limited-edition'],
    fit: 'slim',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#14213d'],
    colorLabels: ['Midnight'],
    sizes: ['6', '8', '10', '12', '14', '16'],
    bodyTypes: ['slim', 'hourglass', 'tall'],
    price: 38500,
    wholesalePrice: 26500,
    minWholesaleQty: 8,
    description:
      'One-piece, all confidence. A tailored sleeveless jumpsuit with a belted waist and clean ankle crop.',
    features: ['Built-in belt', 'Side pockets', 'Hidden back zip'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim6, IMG.womanDenim7, IMG.womanDenim1],
    rating: 4.9,
    reviewCount: 54,
    stock: 18,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Luxury Capsule', 'Limited Drop'],
  },
  {
    name: 'Denim Corset Top',
    category: 'denim-corset',
    categoryLabel: 'Denim Corset',
    collection: ['trending', 'tiktok-viral', 'new-arrivals'],
    fit: 'slim',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    bodyTypes: ['slim', 'hourglass', 'curvy'],
    price: 21500,
    wholesalePrice: 14800,
    minWholesaleQty: 10,
    description:
      'A sculpted denim corset with structured boning and back lace-up detailing. Pair with high-waist palazzo for an unforgettable look.',
    features: ['Internal boning', 'Lace-up back', 'Sweetheart neckline'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim14, IMG.womanDenim6, IMG.womanDenim5],
    rating: 4.8,
    reviewCount: 138,
    stock: 36,
    isNew: true,
    isTrending: true,
    isWholesaleEligible: true,
    tags: ['Viral Fit'],
  },
  {
    name: 'Flare Bell Bottom Jeans',
    category: 'flare-jeans',
    categoryLabel: 'Flare Jeans',
    collection: ['trending', 'streetwear'],
    fit: 'slim',
    waist: 'high',
    wash: 'dark-blue',
    colors: ['#1c3253', '#14213d'],
    colorLabels: ['Dark Blue', 'Midnight'],
    sizes: ['6', '8', '10', '12', '14', '16', '18'],
    bodyTypes: ['slim', 'curvy', 'tall', 'hourglass'],
    price: 25500,
    wholesalePrice: 17600,
    minWholesaleQty: 10,
    description:
      'Slim through the thigh, full bell flare from the knee. The exact ’70s revival shape everyone is searching for.',
    features: ['Slim-to-flare cut', '32" inseam (regular)', 'Heel-skimming hem'],
    fabric: '98% Cotton · 2% Elastane',
    stretchLevel: 3,
    images: [IMG.womanDenim10, IMG.womanDenim9, IMG.womanDenim4],
    rating: 4.8,
    reviewCount: 124,
    stock: 44,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Utility Cargo Denim Pants',
    category: 'cargo-jeans',
    categoryLabel: 'Cargo Jeans',
    collection: ['streetwear', 'trending'],
    fit: 'relaxed',
    waist: 'mid',
    wash: 'stone',
    colors: ['#c0d2e8', '#90b1d4'],
    colorLabels: ['Stone Wash', 'Faded'],
    sizes: ['6', '8', '10', '12', '14', '16', '18'],
    bodyTypes: ['slim', 'athletic', 'rectangle', 'tall'],
    price: 28500,
    wholesalePrice: 19600,
    minWholesaleQty: 10,
    description:
      'Cargo denim with six functional pockets and adjustable hem tabs. Utility meets fashion-forward.',
    features: ['Six cargo pockets', 'Adjustable hem cords', 'Reinforced seams'],
    fabric: '100% Cotton',
    stretchLevel: 1,
    images: [IMG.womanDenim11, IMG.womanDenim2, IMG.womanDenim9],
    rating: 4.7,
    reviewCount: 96,
    stock: 38,
    isTrending: true,
    isWholesaleEligible: true,
  },
  {
    name: 'Denim Maxi Gown',
    category: 'denim-gown',
    categoryLabel: 'Denim Gown',
    collection: ['luxury', 'limited-edition', 'premium-turkish'],
    fit: 'slim',
    wash: 'dark-blue',
    colors: ['#14213d'],
    colorLabels: ['Midnight'],
    sizes: ['6', '8', '10', '12', '14', '16'],
    bodyTypes: ['slim', 'hourglass', 'tall'],
    price: 48500,
    wholesalePrice: 33400,
    minWholesaleQty: 6,
    description:
      'The denim gown that redefines occasion-wear. Floor-grazing, fitted bodice, dramatic sweep. Editorial-grade.',
    features: ['Floor length', 'Boned bodice', 'Hand-finished hem'],
    fabric: '99% Cotton · 1% Elastane',
    stretchLevel: 2,
    images: [IMG.womanDenim13, IMG.womanDenim7, IMG.womanDenim17],
    rating: 5.0,
    reviewCount: 28,
    stock: 9,
    isLimited: true,
    isWholesaleEligible: true,
    tags: ['Luxury Capsule', 'Limited Drop'],
  },
];

function slugify(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export const PRODUCTS: Product[] = baseProducts.map((p, i) => ({
  ...p,
  id: `vj-${(i + 1).toString().padStart(3, '0')}`,
  slug: slugify(p.name),
}));

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCollection(collection: string, limit?: number) {
  const filtered = PRODUCTS.filter((p) => p.collection.includes(collection));
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getRelatedProducts(product: Product, limit = 4) {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && (p.category === product.category || p.fit === product.fit)
  ).slice(0, limit);
}

export const COLLECTIONS: Collection[] = [
  {
    id: 'c1',
    slug: 'new-arrivals',
    name: 'New Arrivals',
    tagline: 'Fresh denim drops',
    description:
      'The very latest from our Turkish denim mill. Limited stock, fast-moving favorites.',
    cover: IMG.womanDenim1,
    productCount: PRODUCTS.filter((p) => p.collection.includes('new-arrivals')).length,
  },
  {
    id: 'c2',
    slug: 'premium-turkish',
    name: 'Premium Turkish Denim',
    tagline: 'Crafted at the mill',
    description:
      'Our signature edit — every piece sourced from Turkey’s most respected denim mills.',
    cover: IMG.womanDenim7,
    productCount: PRODUCTS.filter((p) => p.collection.includes('premium-turkish')).length,
  },
  {
    id: 'c3',
    slug: 'best-sellers',
    name: 'Best Sellers',
    tagline: 'Loved by 10,000+ women',
    description: 'The styles that keep selling out. Restocked weekly.',
    cover: IMG.womanDenim4,
    productCount: PRODUCTS.filter((p) => p.collection.includes('best-sellers')).length,
  },
  {
    id: 'c4',
    slug: 'curvy',
    name: 'Curvy Collection',
    tagline: 'Made for every curve',
    description:
      'Contoured waistbands, sculpting panels, sizes 14–24. Designed with curvy bodies in mind from the start.',
    cover: IMG.womanDenim2,
    productCount: PRODUCTS.filter((p) => p.bodyTypes.includes('curvy')).length,
  },
  {
    id: 'c5',
    slug: 'tiktok-viral',
    name: 'TikTok Viral',
    tagline: 'The pieces breaking the internet',
    description: 'You saw them on your FYP. Now wear them.',
    cover: IMG.womanDenim11,
    productCount: PRODUCTS.filter((p) => p.collection.includes('tiktok-viral')).length,
  },
  {
    id: 'c6',
    slug: 'limited-edition',
    name: 'Limited Edition',
    tagline: 'When they’re gone, they’re gone',
    description: 'Small-batch luxury denim. Numbered drops, no restocks.',
    cover: IMG.womanDenim6,
    productCount: PRODUCTS.filter((p) => p.isLimited).length,
  },
];

// Style category map for "Shop by Style" tiles
export const STYLE_TILES = [
  { name: 'Mom Jeans', slug: 'mom-jeans', image: CATEGORY_IMG.momJeans },
  { name: 'Baggy Jeans', slug: 'baggy-jeans', image: CATEGORY_IMG.baggyJeans },
  { name: 'Palazzo Jeans', slug: 'palazzo-jeans', image: CATEGORY_IMG.palazzoJeans },
  { name: 'Skinny Jeans', slug: 'skinny-jeans', image: CATEGORY_IMG.skinnyJeans },
  { name: 'Wide Leg', slug: 'wide-leg-jeans', image: CATEGORY_IMG.wideLeg },
  { name: 'Flare Jeans', slug: 'flare-jeans', image: CATEGORY_IMG.flare },
  { name: 'Ripped Jeans', slug: 'ripped-jeans', image: CATEGORY_IMG.ripped },
  { name: 'Cargo Jeans', slug: 'cargo-jeans', image: CATEGORY_IMG.cargo },
  { name: 'Denim Jacket', slug: 'denim-jacket', image: CATEGORY_IMG.denimJacket },
  { name: 'Denim Skirt', slug: 'denim-skirt', image: CATEGORY_IMG.denimSkirt },
  { name: 'Denim Shorts', slug: 'denim-shorts', image: CATEGORY_IMG.denimShorts },
  { name: 'Jumpsuits', slug: 'denim-jumpsuit', image: CATEGORY_IMG.denimJumpsuit },
];

export const BODY_TYPE_TILES = [
  { name: 'Petite Fit', slug: 'petite', image: IMG.womanDenim4, blurb: 'Sized down without sizing out the style.' },
  { name: 'Curvy Fit', slug: 'curvy', image: IMG.womanDenim2, blurb: 'Sculpted waistbands, lifted seats, generous through the thigh.' },
  { name: 'Tall Fit', slug: 'tall', image: IMG.womanDenim9, blurb: 'Extra inches in all the right places.' },
  { name: 'Plus Size', slug: 'plus-size', image: IMG.womanDenim7, blurb: 'Premium denim engineered for sizes 16–24.' },
  { name: 'Hourglass', slug: 'hourglass', image: IMG.womanDenim10, blurb: 'Cinches the waist, lifts the rest.' },
  { name: 'Pear Shape', slug: 'pear', image: IMG.womanDenim1, blurb: 'Roomy through the hip with a clean front.' },
];
