import type { Review } from './types';
import { IMG, thumb } from './images';

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    productId: 'vj-001',
    author: 'Adaeze O.',
    location: 'Abuja, NG',
    rating: 5,
    title: 'The waistband alone is worth it',
    body: 'I’m a size 16 with hips and this is the FIRST pair of jeans that fits my waist AND my hips. The denim is thick but soft. Worth every naira.',
    date: '2026-04-12',
    bodyType: 'Curvy',
    sizeBought: '16',
    verified: true,
    image: thumb(IMG.womanDenim2, 400),
  },
  {
    id: 'r2',
    productId: 'vj-002',
    author: 'Chiamaka E.',
    location: 'Abuja, NG',
    rating: 5,
    title: 'Exactly the TikTok fit',
    body: 'Bought after seeing them on @itsvee_jeans page and they look IDENTICAL. So slouchy, fall perfectly.',
    date: '2026-05-02',
    sizeBought: '10',
    verified: true,
  },
  {
    id: 'r3',
    productId: 'vj-004',
    author: 'Tomi A.',
    location: 'Port Harcourt',
    rating: 5,
    title: 'Best skinnies ever',
    body: 'I’ve been searching for skinnies that don’t cut into my belly. These actually contour. The stretch is unreal.',
    date: '2026-04-28',
    bodyType: 'Hourglass',
    sizeBought: '14',
    verified: true,
  },
  {
    id: 'r4',
    productId: 'vj-003',
    author: 'Zainab M.',
    location: 'Kano, NG',
    rating: 5,
    title: 'Office-ready, classy',
    body: 'I wore these palazzos to work and got compliments all day. The drape is gorgeous.',
    date: '2026-04-22',
    sizeBought: '12',
    verified: true,
  },
  {
    id: 'r5',
    productId: 'vj-001',
    author: 'Funmi B.',
    location: 'Ibadan, NG',
    rating: 4,
    title: 'Lovely fit, took a week to arrive',
    body: 'Quality is top tier. Delivery was a bit slow but customer service kept me updated on WhatsApp.',
    date: '2026-03-30',
    bodyType: 'Plus Size',
    sizeBought: '20',
    verified: true,
  },
  {
    id: 'r6',
    productId: 'vj-007',
    author: 'Ngozi K.',
    location: 'Abuja, NG',
    rating: 5,
    title: 'Reseller approved',
    body: 'I run a boutique in Surulere and Vee_jeans is my go-to supplier. Bulk pricing is fair, quality is consistent.',
    date: '2026-05-10',
    verified: true,
  },
];

export function getReviewsForProduct(productId: string) {
  return REVIEWS.filter((r) => r.productId === productId);
}
